syntax = "proto3";

package post;

service PostService {
  rpc CreatePost (PostRequest) returns (PostResponse);
  rpc GetPostById (GetPostRequest) returns (PostResponse);
  rpc GetAllPost (Empty) returns (PostList);
  rpc UpdatePost (UpdatePostRequest) returns (PostResponse);
  rpc DeletePost (GetPostRequest) returns (DeleteResponse);
rpc GetPostsByUser (GetUserPostRequest) returns (PostList);
}

message GetUserPostRequest {
  string userId = 1;
}


message Post {
  string id = 1;
  string title = 2;
  string caption = 3;
    string userId = 4;
}


message PostRequest {
  string title = 1;
  string caption = 2;
    string userId = 3; 
}

message GetPostRequest {
  string id = 1;  
}

message UpdatePostRequest {
  string id = 1;
  string title = 2;
  string caption = 3;
}

message Empty {}

message PostResponse {
  Post post = 1;
}

message PostList {
  repeated Post posts = 1;
}

message DeleteResponse {
  string message = 1;
}
